name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ros:foxy

    steps:
    - uses: actions/checkout@v2

    - uses: ros-tooling/action-ros-ci@0.0.19
      with:
        package-name: simple_planning_simulator
        target-ros2-distro: foxy
        vcs-repo-file-url: autoware.proj.repos
